### ISSUE TITLE
any chance to solve 0.10 errors?

### ISSUE THREAD

**Issue by moebiussurfing** [borg/ofxInterfaceWidgets#1]
hey @borg ,

I am trying to get this working on 0.10. 

What I want is to have a scroll view of several box colors for a color manager/picker.
It seems you have implemented this... Do you think this add-on can help?

This errors are related to 0.9->0.10 changes. I tried to comment the errors but nothing drawing on the screen. I used the included example, but nothing on update/draw like on ofxInterface does..

(EDIT: now I copied the update/draw from the ofxInterface example, added your Button and it's drawing. Now I am looking more inside..
If you have some example or snipped to share should be nice)
 
```
of_v0.10.1_osx_release/addons/ofxInterfaceWidgets/src/widgets/ScrollView.cpp:701:58: No member named 'getInverse' in 'glm::tmat4x4<float, glm::precision::packed_highp>'
of_v0.10.1_osx_release/addons/ofxInterfaceWidgets/src/widgets/ScrollView.cpp:721:22: No member named 'setTransformMatrix' in 'ofxInterface::Node'
```

**Comment by moebiussurfing** [comment]
well, I am closer now, I think.
I added several buttons inside an ScrollView, and then the ScrollView into the ofxInterface scene:
setup():
```
    // SCROLL VIEW:
    ScrollView * scrollV = new ofxInterface::ScrollView();
    scrollV->setSize(200, 500);
    scrollV->setName("scrollView");
    scrollV->setPosition(0, 0, 0);
    scrollV->setPlane(3);
    scrollV->fitContentToWindow(OF_ASPECT_RATIO_IGNORE);
    scrollV->setContentRect(ofRectangle(0, 0, 200, 500));

    for (int i=0; i<50; i++) {
        Button * startBtn = new ofxInterface::Button();
        startBtn->setImages(new ButtonImages("images.jpg"));
        startBtn->setSize(40,40);
        startBtn->setName("vBut"+ofToString(i));
        startBtn->setPosition(0, i * 42, 0);
        startBtn->setPlane(0);
        vBut.push_back(startBtn);
        scrollV->addChild(startBtn);
    }
    scene->addChild(scrollV);
```

On debug mode I can see buttons are responding fine and I can debug the tweens on: 
```
cout << "scrollRect.x  " << scrollRect.x << endl;
cout << "scrollRect.y  " << scrollRect.y << endl;  
```

But I am lost into the matrix transformation to apply into the children buttons inside the ScrollView.. :
```

mat = getMatrixForRect(scrollRectEased);
    
    //this is not working properly on iOS8..not sure if its due to the width/height debacle 
    if(_contentNode->getChildren().size()){

        _contentNode->update(dt);
   
        //this unhides the child...renders it where it is supposed to be
        //in the node space, to an fbo
        _contentNode->setVisible(true);
        
        //move this out
       // _canvas.allocate(getWidth(),getHeight());
        
        _canvas.begin();
        ofClear(255);
        _beginDraw();
        
        ofSetColor(255);
        
        //-TEST
//        ofMatrix4x4 localMat = getLocalTransformMatrix().getInverse();
        auto localMat = getLocalTransformMatrix();
        
        ofPushMatrix();

        //-TEST
        ofMultMatrix(localMat);

        //this is assuming the root scene is at 0,0, else we need to offset...not handling now
        //ofTranslate(-root->getX(),-root->getY());
        _contentNode->render();
        
        _endDraw();
        ofPopMatrix();
        _canvas.end();
        
        _contentNode->setVisible(false);
        
        //this applies the pan/scroll transformation so children will be in correct pos
        //for touch
        //-TEST
//       _contentNode->setTransformMatrix(mat);
    }
```

**Comment by borg** [comment]
```
mat = getMatrixForRect(scrollRectEased);
    
    //this is not working properly on iOS8..not sure if its due to the width/height debacle 
    if(_contentNode->getChildren().size()){

        _contentNode->update(dt);
   
        //this unhides the child...renders it where it is supposed to be
        //in the node space, to an fbo
        _contentNode->setVisible(true);
        

        
        //move this out
        //_canvas.allocate(getWidth(),getHeight());
        
        if(_canvas.isAllocated()){
            _canvas.begin();
            ofClear(255);
            if(_drawBg){
                //premultiplied alphas are washed out in Fbos, helps to fill bg
                ofSetColor(_bgColor);
                ofFill();
                ofDrawRectangle(0,0, getWidth(),getHeight());
            }
            _beginDraw();
            ofSetColor(255);
            ofMatrix4x4 localMat = getGlobalTransformMatrix();
            localMat = localMat.getInverse();
            ofPushMatrix();
            ofMultMatrix(localMat);
            _contentNode->render();
            _endDraw();
            ofPopMatrix();
            _canvas.end();
        }
        _contentNode->setVisible(false);
        
        //this applies the pan/scroll transformation so children will be in correct pos
        ofVec3f pos;
        ofQuaternion rot;
        ofVec3f scale;
        ofQuaternion so;
        mat.decompose(pos, rot, scale, so);

        _contentNode->setPosition(pos);
        _contentNode->setOrientation(rot);
        //_contentNode->setScale(scale);//this is a no no
       
    }

```

Hey, I think I solved this on a recent project...but not sure it's portable. Haven't got time to test, but pushed something that should point it right direction. Please test and PR if needed.
Good luck!
